AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This CloudFormation template creates resources for the RSVP project in a development environment.
  It provisions an S3 bucket to store event assets and an IAM user with specific permissions to access only this bucket.
  The IAM user has PutObject, GetObject, and DeleteObject permissions for the objects within the bucket.
  Additionally, GetObject permission is publicly available for all objects in the bucket.

Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "rsvp-user-${AWS::AccountId}"

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "rsvp-dev-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - "GET"
              - "PUT"
              - "DELETE"
            AllowedHeaders:
              - "*"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"
            Principal: "*"
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource: !Sub "${S3Bucket.Arn}/*"
            Principal:
              AWS: !GetAtt IAMUser.Arn

  IAMUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "RSVPBucketAccessPolicy"
      Users:
        - !Ref IAMUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

Outputs:
  AWSAccessKey:
    Value: !Sub "AWS_ACCESS_KEY=${IAMAccessKey}"
    Description: "AWS Access Key for the IAM User"

  AWSSecretKey:
    Value: !Sub "AWS_SECRET_KEY=${IAMAccessKey.SecretAccessKey}"
    Description: "AWS Secret Key for the IAM User"

  AWSRegion:
    Value: !Sub "AWS_REGION=${AWS::Region}"
    Description: "AWS Region where the bucket is created"

  AWSBucketName:
    Value: !Sub "AWS_BUCKET_NAME=${S3Bucket}"
    Description: "Name of the created S3 bucket"
